Repository mattermost/mattermost-load-test, pull requests merged in 2018-06, with the labels that each got.

#71 MM-10728 Add support for kubernetes
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  cmd/ltops/create.go
  cmd/ltops/delete.go
  cmd/ltops/deploy.go
  cmd/ltops/load.go
  cmd/ltops/loadtest.go
  cmd/ltops/root.go
  cmd/ltops/ssh.go
  cmd/ltops/status.go
  glide.lock
  glide.yaml
  kubernetes/cluster.go
  kubernetes/cluster_connect.go
  kubernetes/cluster_create.go
  kubernetes/cluster_deploy.go
  kubernetes/cluster_loadtest.go
  ltops/cluster.go
  ltops/utils.go
  sshtools/kubetools.go
  terraform/cluster.go
  terraform/cluster_create.go
  terraform/cluster_deploy.go
  terraform/cluster_load.go
Labels: 1: Dev Review

#72 MM-10233: Include custom schemes in the loadtests.
  loadtest/bulkload.go
  loadtestconfig.default.json
Labels: 1: Dev Review

#73 Stop manually adding users to town square in bulk load
  loadtest/bulkload.go
Labels: 1: Dev Review

#74 Configuration updates to running load tests with ltops/kubernetes
  kubernetes/cluster_deploy.go
Labels: 1: Dev Review

#75 Use mlog to print thread splitting numbers
  loadtest/thread_split.go
Labels: 1: Dev Review

#76 Update ltops kubes config to configure MySQL master/slaves, bump image to 4.10.1 and user count to 30k
  kubernetes/cluster_deploy.go
  kubernetes/cluster_loadtest.go
Labels: 2: Ready to Merge

#77 Preamble for load test profiles
  README.md
  cmd/ltops/deploy.go
  cmd/ltops/load.go
  kubernetes/chart_config.go
  kubernetes/cluster_deploy.go
  kubernetes/cluster_profile.go
  ltops/cluster.go
  ltops/deploy.go
  ltops/profile.go
  terraform/cluster_deploy.go
Labels: 1: Dev Review

#78 Add post loading, bulk load skipping, helm config specifying and more to ltops/kubes
  cmd/ltops/deploy.go
  cmd/ltops/loadtest.go
  cmd/ltops/status.go
  kubernetes/chart_config.go
  kubernetes/cluster_deploy.go
  kubernetes/cluster_loadtest.go
  kubernetes/cluster_profile.go
  ltops/cluster.go
  ltops/deploy.go
  ltops/loadtest.go
  terraform/cluster_loadtest.go
Labels: 2: Ready to Merge

#80 MM-10481 Increase status polling rate to more closely match real clients
  loadtest/entity.go
Labels: 1: Dev Review

#82 Dont set Schemes on team/channel if no schemes being generated.
  loadtest/bulkload.go
Labels: 1: Dev Review

#83 setcap for mattermost binary in addition to platform
  cmd/ltops/status.go
  terraform/cluster_deploy.go
Labels: 1: Dev Review

#86 Improvments to first time setup
  README.md
  kubernetes/cluster_connect.go
  kubernetes/cluster_loadtest.go
Labels: 1: Dev Review

#88 terraform: actually use ltops profile
  terraform/cluster.tf
  terraform/terraformfile.go
Labels: 1: Dev Review

#87 hard-code model.SCHEME_SCOPE_(TEAM|CHANNEL)
  loadtest/bulkload.go
Labels: 1: Dev Review

#89 loadtest: more channels browser
  cmd/loadtest/loadtest.go
  loadtest/entity.go
  loadtest/setup_server.go
  loadtest/tests.go
Labels: 2: Ready to Merge

#95 Additional pprof fixes
  loadtest/run.go
  terraform/cluster_deploy.go
Labels: 2: Ready to Merge

#97 avoid JSON serialization error when all API requests fail
  loadtest/client_timing_stats.go
Labels: 2: Ready to Merge

#65 Adding support for channel search and autocomplete.
  cmd/loadtest/loadtest.go
  loadtest/tests.go
Labels: 2: Ready to Merge

#100 Show 95th percentile, among other improvements.
  cmd/ltparse/results.go
  loadtest/client_timing_stats.go
  ltparse/markdown.go
  ltparse/results.go
  ltparse/text.go
Labels: 1: Dev Review

#99 allow tuning *IdleConn*, with higher initial defaults
  loadtest/client.go
  loadtest/config.go
  loadtest/run.go
  loadtest/setup_server.go
  loadtestconfig.default.json
Labels: 2: Ready to Merge

#94 terraform: allow all db:3306 ingress
  terraform/cluster.tf
  terraform/terraformfile.go
Labels: 2: Ready to Merge

#92 Fix other permissions issues
  loadtest/bulkload.go
Labels: 1: Dev Review, Awaiting PR
